notifications:
  email: false
dist: xenial
language: python
cache: pip
services:
  - postgresql
env:
  - DJANGO_SETTINGS_MODULE=hsf.test_settings
python:
  - "3.7"
install: 
  - "pip install pipenv"
  - "pipenv sync --dev"
script: "make ci"
