notifications:
  email: false
dist: xenial
language: python
cache: pip
services:
- postgresql
env:
  global:
  - DJANGO_SETTINGS_MODULE=hsf.test_settings
  - DOCKER_USERNAME=russss
  - secure: ewJsScaGCIUriU77ytUWWb4RKhhKTHw4lZsCdoN+VU59hHpwmMAMHwaVcReiITKOSnT2UqTtBCIFw+9ZullGmYKqgNgn9+qiWUT3d08iOilAuKl0BcWyU7VXCwbmq2pbhi4ubZHBt1dGJfSJbqvcBKhro5kK6v7T43W/859wKDDznTl5trqTJoPyC56L+40hqWAfuhnOqk9dRsw9vFFfgKcG4DVjM7thIyFW79b9/EqapKif/BO6bQJoOA7j8ZGu0SqMKqqWHMwDPSmb9goKxb9TiqX0/aXcOYjGj8DInW5ShMxOgyw8xOLmCd44A0cRlroYanYiicWDMudY0LbVt2GEFL24W3MoZM6LSsK7eepDf5iLNVlw/dpAcJAxu/CJY6dRcgGjq6jzry+XDcOIlvqJReLUCVOWIQbeMOZoFUr6W2kkbOpt8sBn+oD/0AjNXCAgTOQq+HVi4KnTMnDeRgZc1sso9FDBZWRp8mLtuDaZtjAOYgJX7Nyw5groJeBuVtx4O2tNWhrMcfgA9AIrvJNtraOohHjPvfaaJiHlnawl99vUjVDnhy4Etb/mLTfKWjQJzhMKsL3fh7vWuKox7aW+5JT4amGb7lHuNi9D0m3uj76Es6exUcConddf44oR7AV6PqJm3aUqgDLx6/EXy6nDLrKRXAbfZmgdZObUKHM=
python:
- '3.7'
install:
- pip install pipenv
- pipenv sync --dev
script: make ci
deploy:
  provider: script
  script: "./docker/docker_login.sh && make deploy"
  on:
    branch: master
