version: "3.7"
services:
  web:
    build: 
      context: "./"
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: "hsf.dev_settings"
    networks:
      - hsf
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
  db:
    image: "postgres:15"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - hsf
networks:
  hsf:
