# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('longname', models.CharField(max_length=200)),
                ('town', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('havePremises', models.BooleanField()),
                ('townNotInName', models.BooleanField()),
                ('addressFirstLine', models.CharField(max_length=250)),
                ('postcode', models.CharField(max_length=9)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10, verbose_name=b'latitude')),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10, verbose_name=b'longitude')),
                ('mainWebsiteUrl', models.URLField()),
                ('logoImageUrl', models.URLField()),
                ('status', models.CharField(max_length=20)),
                ('classification', models.CharField(max_length=20)),
            ],
        ),
    ]
