# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='addressFirstLine',
            new_name='address_first_line',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='havePremises',
            new_name='have_premises',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='logoImageUrl',
            new_name='logo_image_url',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='mainWebsiteUrl',
            new_name='main_website_url',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='townNotInName',
            new_name='town_not_in_name',
        ),
        migrations.AddField(
            model_name='space',
            name='changed_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
