# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170406_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='address_first_line',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='space',
            name='logo_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='main_website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='space',
            name='postcode',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='space',
            name='town',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
