# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_space'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='space',
            options={'ordering': ['name']},
        ),
    ]
