# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170415_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='longname',
        ),
    ]
