# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_space_longname'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
