# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170415_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('STARTING', 'Starting'), ('SUSPENDED', 'Suspended'), ('DEFUNCT', 'DEFUNCT')], default='ACTIVE', max_length=20),
        ),
    ]
