# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170415_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='country',
            field=models.CharField(choices=[('England', 'England'), ('Guernsey', 'Guernsey'), ('Ireland', 'Ireland'), ('Scotland', 'Scotland'), ('Wales', 'Wales')], default='ENGLAND', max_length=50),
        ),
        migrations.AlterField(
            model_name='space',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Starting', 'Starting'), ('Suspended', 'Suspended'), ('Defunct', 'DEFUNCT')], default='ACTIVE', max_length=20),
        ),
    ]
