# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20170415_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='town_not_in_name',
        ),
        migrations.AlterField(
            model_name='space',
            name='have_premises',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='space',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
