# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20170415_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='space_approver',
            field=models.EmailField(blank=True, max_length=254, verbose_name='space approver email address'),
        ),
        migrations.AddField(
            model_name='user',
            name='space_request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='space_status',
            field=models.CharField(choices=[('Blank', 'Blank'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Blank', max_length=8),
        ),
    ]
