# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20170418_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='space_request_key',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
