# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_user_space_request_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gocardless_redirect_flow_id',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AddField(
            model_name='user',
            name='gocardless_session_token',
            field=models.CharField(default='0509f6f9a2fa42bdb3a4c51b31a32e3d', max_length=33),
        ),
    ]
