# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20170418_2108'),
        ('main', '0015_user_space_request_key'),
    ]

    operations = [
    ]
