# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20170421_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gocardless_customer_id',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='gocardless_mandate_id',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='gocardless_session_token',
            field=models.CharField(default='1f2e33d9b1cf45ffbc47daaea38b1143', max_length=33),
        ),
    ]
