# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20170421_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member_status',
            field=models.CharField(choices=[('Blank', 'Blank'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Blank', max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='member_type',
            field=models.CharField(choices=[('None', 'None'), ('Supporter', 'Supporter'), ('Representative', 'Representative')], default='None', max_length=14),
        ),
        migrations.AlterField(
            model_name='user',
            name='gocardless_session_token',
            field=models.CharField(default='a9f49a557dc0465c9b811693c19363d1', max_length=33),
        ),
    ]
