# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20170421_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member_fee',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='gocardless_session_token',
            field=models.CharField(default='7b13f5d6237749aba1541454199569c4', max_length=33),
        ),
    ]
