# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20170421_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gocardless_session_token',
            field=models.CharField(default='', max_length=33),
        ),
    ]
