# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-21 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20170421_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='member_statement',
            field=models.TextField(blank=True),
        ),
    ]
