# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_user_member_statement'),
        ('main', '0016_merge_20170421_2343'),
    ]

    operations = [
    ]
