# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_user_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='GocardlessPayment',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('charge_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=26)),
                ('amount_refunded', models.IntegerField()),
                ('reference', models.CharField(max_length=10)),
                ('payout_date', models.DateField(default=django.utils.timezone.now)),
                ('mandate_id', models.CharField(max_length=16)),
                ('creditor_id', models.CharField(max_length=16)),
                ('payout_id', models.CharField(max_length=16)),
            ],
        ),
    ]
