# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_gocardlesspayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gocardlesspayment',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AlterField(
            model_name='gocardlesspayment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gocardlesspayment',
            name='amount_refunded',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gocardlesspayment',
            name='creditor_id',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='gocardlesspayment',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gocardlesspayment',
            name='mandate_id',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='gocardlesspayment',
            name='payout_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gocardlesspayment',
            name='payout_id',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='gocardlesspayment',
            name='reference',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
