# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 22:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20170423_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='gocardlesspayment',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Space'),
        ),
        migrations.AddField(
            model_name='gocardlesspayment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
