# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20170423_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gocardlesspayment',
            name='charge_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
