# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 14:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20170423_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='GocardlessMandate',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(max_length=26)),
                ('creditor_id', models.CharField(blank=True, max_length=16)),
                ('customer_id', models.CharField(blank=True, max_length=16)),
                ('customer_bank_account_id', models.CharField(blank=True, max_length=16)),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Space')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='gocardlesspayment',
            name='mandate_id',
        ),
        migrations.AddField(
            model_name='gocardlesspayment',
            name='mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.GocardlessMandate'),
        ),
    ]
