# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20170424_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportermembership',
            name='expired_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='supportermembership',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='supportermembership',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=8),
        ),
    ]
