# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20170424_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gocardlessmandate',
            name='redirect_flow_id',
        ),
        migrations.RemoveField(
            model_name='gocardlessmandate',
            name='session_token',
        ),
        migrations.AddField(
            model_name='supportermembership',
            name='redirect_flow_id',
            field=models.CharField(blank=True, max_length=33),
        ),
        migrations.AddField(
            model_name='supportermembership',
            name='session_token',
            field=models.CharField(default='', max_length=33),
        ),
        migrations.AlterField(
            model_name='gocardlessmandate',
            name='status',
            field=models.CharField(blank=True, max_length=26),
        ),
    ]
