# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20170424_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportermembership',
            name='approval_request_count',
            field=models.IntegerField(default=0),
        ),
    ]
