# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_supportermembership_approval_request_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gocardlesspayment',
            name='space',
        ),
        migrations.RemoveField(
            model_name='gocardlesspayment',
            name='user',
        ),
        migrations.AlterModelTable(
            name='gocardlessmandate',
            table='main_GocardlessMandate',
        ),
        migrations.AlterModelTable(
            name='gocardlesspayment',
            table='main_GocardlessPayment',
        ),
        migrations.AlterModelTable(
            name='space',
            table='main_Space',
        ),
        migrations.AlterModelTable(
            name='supportermembership',
            table='main_SupporterMembership',
        ),
        migrations.AlterModelTable(
            name='user',
            table='main_User',
        ),
    ]
