# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20170428_1916'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gocardlessmandate',
            table=None,
        ),
        migrations.AlterModelTable(
            name='gocardlesspayment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='space',
            table=None,
        ),
        migrations.AlterModelTable(
            name='supportermembership',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
