# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20170428_1917'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gocardlessmandate',
            table='GocardlessMandate',
        ),
        migrations.AlterModelTable(
            name='gocardlesspayment',
            table='GocardlessPayment',
        ),
        migrations.AlterModelTable(
            name='space',
            table='Space',
        ),
        migrations.AlterModelTable(
            name='supportermembership',
            table='SupporterMembership',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
