# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20170428_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportermembership',
            name='expired_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='supportermembership',
            name='started_at',
            field=models.DateField(null=True),
        ),
    ]
