# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20170429_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gocardlesspayment',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
