# Generated by Django 2.0.9 on 2018-11-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20181124_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gocardlessmandate',
            name='creditor_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gocardlessmandate',
            name='customer_bank_account_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gocardlessmandate',
            name='customer_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gocardlessmandate',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gocardlessmandate',
            name='reference',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gocardlessmandate',
            name='status',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gocardlesspayment',
            name='creditor_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gocardlesspayment',
            name='currency',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='gocardlesspayment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gocardlesspayment',
            name='id',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='gocardlesspayment',
            name='idempotency_key',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gocardlesspayment',
            name='payout_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gocardlesspayment',
            name='reference',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='gocardlesspayment',
            name='status',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='supportermembership',
            name='redirect_flow_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='supportermembership',
            name='session_token',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='supportermembership',
            name='status',
            field=models.TextField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending'),
        ),
    ]
