# Generated by Django 2.0.13 on 2019-07-01 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_char_to_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending')),
                ('approval_request_count', models.IntegerField(default=0)),
                ('fee', models.DecimalField(decimal_places=2, default=20.0, max_digits=8)),
                ('statement', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateField(null=True)),
                ('expired_at', models.DateField(null=True)),
                ('redirect_flow_id', models.TextField(blank=True)),
                ('session_token', models.TextField(default='')),
            ],
            options={
                'db_table': 'spacemembership',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='space_status',
            field=models.CharField(choices=[('Blank', 'Blank'), ('Pending', 'Pending'), ('Emailed', 'Emailed'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Blank', max_length=8),
        ),
        migrations.AddField(
            model_name='spacemembership',
            name='applied_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spacemembership',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Space'),
        ),
    ]
