# Generated by Django 2.0.13 on 2019-07-02 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20190701_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='gocardlessmandate',
            name='space_membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SpaceMembership'),
        ),
    ]
