name: Main

on:
    [push, pull_request]

env:
    DJANGO_SETTINGS_MODULE: hsf.test_settings
    COMPOSE_INTERACTIVE_NO_CLI: 1

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Start containers
              uses: isbang/compose-action@v1.4.1
              with:
                up-flags: "--build"
                down-flags: "--volumes"
            - name: Run tests
              run: |
                docker-compose exec web poetry run flake8 ./main
                docker-compose exec web poetry run ./manage.py test