name: UKHF Website CI

on:
    [push, pull_request]

env:
    DJANGO_SETTINGS_MODULE: hsf.test_settings

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.7'
            - name: Setup Postgres
              uses: CasperWA/postgresql-action@v1.2
              with:
                postgresql version: '9.5'
                postgresql db: postgres
                postgresql user: postgres
                postgresql password: postgres
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pipenv
                pipenv sync --dev
            - name: Lint with flake8
              run: |
                pipenv run flake8 ./main
                pipenv run ./manage.py test